archives:
- id: binary
  files:
  - LICENSE
  format: tar.gz
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    386:    32bit
    amd64:  64bit
    darwin: macOS
    linux:  Linux

brews:
- name: stash
  description: Stash your bash history.
  homepage: https://github.com/kamilsk/stash
  commit_author:
    name:  Kamil Samigullin
    email: kamil@samigullin.info
  folder: Formula
  github:
    name:  homebrew-tap
    owner: kamilsk

builds:
- binary: stash
  env:
  - CGO_ENABLED=0
  goarch:
  - 386
  - amd64
  goos:
  - darwin
  - linux
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  main: .

checksum: { name_template: checksums.txt }

release:
  draft: false
  github:
    name:  stash
    owner: kamilsk
